[package]
name = "loc-place-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.12", features = ["macros", "webhooks-axum"] }
log = "0.4"
pretty_env_logger = "0.5.0"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
reqwest = "0.11.17"
regex = "1.8.1"
once_cell = "1.17.1"
serde_json = "1.0.96"
axum = "0.6.18"
axum-prometheus = "0.3.3"
hyper = "1.0.0-rc.3"
futures = "0.3.28"
tonic = "0.10.2"
prost = "0.12.3"
prost-types = "0.12.3"
prost-wkt-types = "0.5.0"
prometheus = "0.13.3"
uuid = { version = "1.3.3", features = ["v4", "fast-rng"] }
strum = "0.24.1"
strum_macros = "0.24.3"
rust-i18n = "2.1.0"
async-trait = "0.1.68"
http-cache = { version = "0.11.0", default-features = false, features = ["manager-moka"] }
http-cache-reqwest = { version = "0.9.0", default-features = false, features = ["manager-moka"] }
reqwest-middleware = "0.2.2"
anyhow = "1.0.71"
redis = { version = "0.23.3", features = ["ahash", "tokio-comp", "connection-manager"] }
mobc = "0.8.1"
mobc-redis = "0.8.0"
chashmap = "2.2.2"
derive_more = { version = "1.0.0-beta.6", features = ["display", "from", "constructor", "error"] }
thiserror = "1.0.56"
sha256 = "1.5.0"

[dev-dependencies]
testcontainers = "0.14.0"

[build-dependencies]
tonic-build = "0.10.2"
