[package]
name = "loc-place-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.12", default-features = false, features = ["macros", "webhooks-axum", "rustls", "ctrlc_handler"] }
log = "0.4"
pretty_env_logger = "0.5.0"
tokio = { version =  "1.35.1", default-features = false, features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.11.23", default-features = false, features = ["rustls-tls"] }
regex = "1.10.2"
once_cell = "1.19.0"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
http = "1.0.0"
mime = "0.3.17"
axum = "0.6.20"
axum-prometheus = "0.3.4"
hyper = "1.1.0"
futures = "0.3.30"
tonic = "0.10.2"
prost = "0.12.3"
prost-types = "0.12.3"
prost-wkt-types = "0.5.0"
prometheus = "0.13.3"
uuid = { version = "1.6.1", features = ["v4", "fast-rng"] }
strum = "0.25.0"
strum_macros = "0.25.3"
rust-i18n = "2.3.0"
async-trait = "0.1.77"
http-cache = { version = "0.11.0", default-features = false, features = ["manager-moka"] }
http-cache-reqwest = { version = "0.9.0", default-features = false, features = ["manager-moka"] }
reqwest-middleware = "0.2.4"
anyhow = "1.0.79"
redis = { version = "0.24.0", features = ["ahash", "tokio-comp", "connection-manager"] }
mobc = "0.8.3"
mobc-redis = "0.8.2"
chashmap = "2.2.2"
derive_more = { version = "1.0.0-beta.6", features = ["display", "from", "constructor", "error"] }
thiserror = "1.0.56"
sha256 = "1.5.0"

[dev-dependencies]
testcontainers = "0.14.0"

[build-dependencies]
tonic-build = "0.10.2"
